from config import settings
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

sender_email = "pablo@nomades.com.ar"
receiver_email = "pablushka@nomades.com.ar"

message = MIMEMultipart("alternative")
message["Subject"] = "multipart test"
message["From"] = settings('MAIL_FROM')
message["To"] = receiver_email

# app.config['MAIL_SERVER'] = settings('MAIL_SERVER')
# app.config['MAIL_PORT'] = settings('MAIL_PORT')
# app.config['MAIL_USERNAME'] = settings('MAIL_USERNAME')
# app.config['MAIL_PASSWORD'] = settings('MAIL_PASSWORD')
# app.config['MAIL_USE_TLS'] = settings('MAIL_STARTTLS')
# app.config['MAIL_USE_SSL'] = settings('MAIL_SSL_TLS')


def send_registration_email(name: str, qr: str, secret: str, user_id: int):
    text = "Abra este email en un cliente de correo que soporte HTML"
    html = f"""
    <html>
    <body>
    <p>Hi {name},</p>
    <p>Thank you for registering with us.</p>
    <H1> Step 1</h1>
    <p>Please scan the code to setup your authentication app</p>
    <p> If you don't have an authentication app, please install one from the following links:</p>
    <p> <a href="https://keeweb.info/">KeeWeb</a> </p>
    <p> <a href="https://freeotp.github.io/">freeOTP</a> </p>


    <img src="data:image/png;base64, {qr}" alt="QR Code" width="300" height="300">

    <p> Your secret is: {secret} </p>
    <h3>KEEP IT SAFE</h3>

    <H1> Step 2</h1>
    <p> Please follow this link and enter the code generated by your authentication app</p>
    <p> <a href="http://localhost:2000/users/verify/{user_id}">Verify your account</a> </p>
    """

    # Turn these into plain/html MIMEText objects
    part1 = MIMEText(text, "plain")
    part2 = MIMEText(html, "html")

    # Add HTML/plain-text parts to MIMEMultipart message
    # The email client will try to render the last part first
    message.attach(part1)
    message.attach(part2)

    # Create secure connection with server and send email
    context = ssl.create_default_context()
    print(settings)
    with smtplib.SMTP_SSL("smtp.fastmail.com", 465) as server:
        server.login("pablo@nomades.com.ar", "q6cxv27x4y5bknwl")
        server.sendmail(
            sender_email, receiver_email, message.as_string()
        )
