"""Creacion de DB

Revision ID: 097e8352344f
Revises: 
Create Date: 2022-11-08 20:10:38.137703

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '097e8352344f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('text', sa.String(length=500), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
