
GET http://127.0.0.1:5000/events HTTP/1.1


###

GET http://127.0.0.1:5000/events/25-01-2023/Adios/no_hay_nada HTTP/1.1

###

POST http://127.0.0.1:5000/events HTTP/1.1
Content-Type: application/json

{
    "date": "13-12-2022",
    "title": "Lorem ipsum",
    "text": "lorewm ipsum"
}

###

PATCH http://127.0.0.1:5000/events HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "date": "25-01-2022",
    "title": "Modificado desde un patch",
    "text": "texto_evento"
}

###

DELETE http://127.0.0.1:5000/events/999 HTTP/1.1
