POST http://127.0.0.1:5000/gallery HTTP/1.1
Content-Type: application/json

{
    "title": "Lorem ",
    "flyer": "c:\\misdocumentos\\fotos.jpg",
    "date": "2020-01-10"
}
###

GET http://127.0.0.1:5000/galleries HTTP/1.1

###

PATCH http://127.0.0.1:5000/gallery HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "flyer": "1.jpg",
    "title": "esto esta bien verdad?",
    "date": "2020-01-10"

}

###

DELETE http://127.0.0.1:5000/gallery/6  HTTP/1.1


###

PATCH http://127.0.0.1:5000/gallery/1 HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "flyer": "1.png",
    "title": "esto esta bien verdad? lalala",
    "date": "20-01-2010",
    "photos": ["Captura_de_pantalla_106.png"]

}