
GET http://localhost:5000/users HTTP/1.1

###

POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Pablito4",
    "email": "pablushka@nomades.com.ar",
    "last_login": "31-01-2023",
    "is_active": true,
    "is_admin": false
}

###

# gAAAAABkBiAcIsiM9ECninJSl4iVKq8nzRHouezzbPPldDTYZR8Fmy551tsXuTYuQftQV_C2fLx3HKluG5pMLnTuXlhPnkKqRA==
PATCH http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "name": "Jorgito",
    "email": "jorgito@nomades.com",
    "last_login": "31-01-2023",
    "is_admin": false,
    "password": "tigre"
}

###

DELETE http://localhost:5000/users/2 HTTP/1.1

###

PATCH http://localhost:5000/users/2 HTTP/1.1

###

GET http://localhost:5000/users/2 HTTP/1.1
