"""photo galleri models

Revision ID: 302291ec87ca
Revises: 6863361596d3
Create Date: 2023-07-13 15:10:02.717327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302291ec87ca'
down_revision = '6863361596d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flyer', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('gallery')
    # ### end Alembic commands ###
