"""Upgrade model defaults

Revision ID: 378dc2dbad3a
Revises: 01ce6a1922fc
Create Date: 2023-01-03 21:21:13.861406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378dc2dbad3a'
down_revision = '01ce6a1922fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
