"""add column photo type

Revision ID: 73dccbbfe705
Revises: c2ffd5c4fa23
Create Date: 2023-08-01 11:50:48.938160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dccbbfe705'
down_revision = 'c2ffd5c4fa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
