"""change password for secret

Revision ID: c12a75116a51
Revises: 378dc2dbad3a
Create Date: 2023-03-06 14:11:17.613543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12a75116a51'
down_revision = '378dc2dbad3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('secret', sa.String(length=254), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('password', sa.VARCHAR(length=254), nullable=False))
        batch_op.drop_column('secret')

    # ### end Alembic commands ###
