"""add gallery date

Revision ID: c2ffd5c4fa23
Revises: f9b3f461259d
Create Date: 2023-07-18 10:18:14.073707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ffd5c4fa23'
down_revision = 'f9b3f461259d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
